// ⚠️ COPIA EXACTA de src/data/paises.ts (app móvil) — mismas cadenas de texto, mismo orden. No
// reimplementar por separado (mismo costo escrito ya documentado para numeroEmpleadoAEmail() en
// dashboard/lib/choferes.ts): un valor de `pais_nacimiento` cargado desde el Dashboard tiene que
// ser comparable con uno cargado desde la app antes de que el registro móvil se deshabilitara
// (Hallazgo #25) — si las dos listas divergen, esa comparación deja de tener sentido. Listado
// ISO 3166-1 (nombre en español).
export const PAISES: string[] = [
  "Afganistán",
  "Albania",
  "Alemania",
  "Andorra",
  "Angola",
  "Antigua y Barbuda",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaiyán",
  "Bahamas",
  "Bangladés",
  "Barbados",
  "Baréin",
  "Bélgica",
  "Belice",
  "Benín",
  "Bielorrusia",
  "Birmania",
  "Bolivia",
  "Bosnia y Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunéi",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Bután",
  "Cabo Verde",
  "Camboya",
  "Camerún",
  "Canadá",
  "Catar",
  "Chad",
  "Chile",
  "China",
  "Chipre",
  "Ciudad del Vaticano",
  "Colombia",
  "Comoras",
  "Corea del Norte",
  "Corea del Sur",
  "Costa de Marfil",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Dinamarca",
  "Dominica",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Emiratos Árabes Unidos",
  "Eritrea",
  "Eslovaquia",
  "Eslovenia",
  "España",
  "Estados Unidos",
  "Estonia",
  "Esuatini",
  "Etiopía",
  "Filipinas",
  "Finlandia",
  "Fiyi",
  "Francia",
  "Gabón",
  "Gambia",
  "Georgia",
  "Ghana",
  "Granada",
  "Grecia",
  "Guatemala",
  "Guinea",
  "Guinea-Bisáu",
  "Guinea Ecuatorial",
  "Guyana",
  "Haití",
  "Honduras",
  "Hungría",
  "India",
  "Indonesia",
  "Irak",
  "Irán",
  "Irlanda",
  "Islandia",
  "Islas Marshall",
  "Islas Salomón",
  "Israel",
  "Italia",
  "Jamaica",
  "Japón",
  "Jordania",
  "Kazajistán",
  "Kenia",
  "Kirguistán",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letonia",
  "Líbano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Madagascar",
  "Malasia",
  "Malaui",
  "Maldivas",
  "Malí",
  "Malta",
  "Marruecos",
  "Mauricio",
  "Mauritania",
  "México",
  "Micronesia",
  "Moldavia",
  "Mónaco",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Níger",
  "Nigeria",
  "Noruega",
  "Nueva Zelanda",
  "Omán",
  "Países Bajos",
  "Pakistán",
  "Palaos",
  "Panamá",
  "Papúa Nueva Guinea",
  "Paraguay",
  "Perú",
  "Polonia",
  "Portugal",
  "Reino Unido",
  "República Centroafricana",
  "República Checa",
  "República del Congo",
  "República Democrática del Congo",
  "República Dominicana",
  "Ruanda",
  "Rumanía",
  "Rusia",
  "Samoa",
  "San Cristóbal y Nieves",
  "San Marino",
  "San Vicente y las Granadinas",
  "Santa Lucía",
  "Santo Tomé y Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leona",
  "Singapur",
  "Siria",
  "Somalia",
  "Sri Lanka",
  "Sudáfrica",
  "Sudán",
  "Sudán del Sur",
  "Suecia",
  "Suiza",
  "Surinam",
  "Tailandia",
  "Tanzania",
  "Tayikistán",
  "Timor Oriental",
  "Togo",
  "Tonga",
  "Trinidad y Tobago",
  "Túnez",
  "Turkmenistán",
  "Turquía",
  "Tuvalu",
  "Ucrania",
  "Uganda",
  "Uruguay",
  "Uzbekistán",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Yibuti",
  "Zambia",
  "Zimbabue",
];

// spec_telefono_pais_selector.md: mapa de cada uno de los 193 nombres de arriba a su código ISO
// 3166-1 alpha-2, para poder pedirle a libphonenumber-js el código de marcación
// (getCountryCallingCode(iso), ver dashboard/lib/telefono-pais.ts) — paises.ts no traía esto
// antes de esta spec. Construido una sola vez cruzando programáticamente los 193 nombres contra
// los nombres en español de `i18n-iso-countries` (174 matchearon exacto; los otros 19 usan una
// transliteración distinta en esta lista — ej. "Bangladés" vs "Bangladesh" de esa librería — y se
// resolvieron a mano, confirmando en cada caso que el código elegido tiene un `getCountryCallingCode`
// válido). Nunca se traducen los 193 nombres en sí: siguen siendo los mismos de PAISES, en español,
// compartidos con la app móvil.
export const ISO_POR_PAIS: Record<string, string> = {
  Afganistán: "AF",
  Albania: "AL",
  Alemania: "DE",
  Andorra: "AD",
  Angola: "AO",
  "Antigua y Barbuda": "AG",
  "Arabia Saudita": "SA",
  Argelia: "DZ",
  Argentina: "AR",
  Armenia: "AM",
  Australia: "AU",
  Austria: "AT",
  Azerbaiyán: "AZ",
  Bahamas: "BS",
  Bangladés: "BD",
  Barbados: "BB",
  Baréin: "BH",
  Bélgica: "BE",
  Belice: "BZ",
  Benín: "BJ",
  Bielorrusia: "BY",
  Birmania: "MM",
  Bolivia: "BO",
  "Bosnia y Herzegovina": "BA",
  Botsuana: "BW",
  Brasil: "BR",
  Brunéi: "BN",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Bután: "BT",
  "Cabo Verde": "CV",
  Camboya: "KH",
  Camerún: "CM",
  Canadá: "CA",
  Catar: "QA",
  Chad: "TD",
  Chile: "CL",
  China: "CN",
  Chipre: "CY",
  "Ciudad del Vaticano": "VA",
  Colombia: "CO",
  Comoras: "KM",
  "Corea del Norte": "KP",
  "Corea del Sur": "KR",
  "Costa de Marfil": "CI",
  "Costa Rica": "CR",
  Croacia: "HR",
  Cuba: "CU",
  Dinamarca: "DK",
  Dominica: "DM",
  Ecuador: "EC",
  Egipto: "EG",
  "El Salvador": "SV",
  "Emiratos Árabes Unidos": "AE",
  Eritrea: "ER",
  Eslovaquia: "SK",
  Eslovenia: "SI",
  España: "ES",
  "Estados Unidos": "US",
  Estonia: "EE",
  Esuatini: "SZ",
  Etiopía: "ET",
  Filipinas: "PH",
  Finlandia: "FI",
  Fiyi: "FJ",
  Francia: "FR",
  Gabón: "GA",
  Gambia: "GM",
  Georgia: "GE",
  Ghana: "GH",
  Granada: "GD",
  Grecia: "GR",
  Guatemala: "GT",
  Guinea: "GN",
  "Guinea-Bisáu": "GW",
  "Guinea Ecuatorial": "GQ",
  Guyana: "GY",
  Haití: "HT",
  Honduras: "HN",
  Hungría: "HU",
  India: "IN",
  Indonesia: "ID",
  Irak: "IQ",
  Irán: "IR",
  Irlanda: "IE",
  Islandia: "IS",
  "Islas Marshall": "MH",
  "Islas Salomón": "SB",
  Israel: "IL",
  Italia: "IT",
  Jamaica: "JM",
  Japón: "JP",
  Jordania: "JO",
  Kazajistán: "KZ",
  Kenia: "KE",
  Kirguistán: "KG",
  Kiribati: "KI",
  Kuwait: "KW",
  Laos: "LA",
  Lesoto: "LS",
  Letonia: "LV",
  Líbano: "LB",
  Liberia: "LR",
  Libia: "LY",
  Liechtenstein: "LI",
  Lituania: "LT",
  Luxemburgo: "LU",
  Madagascar: "MG",
  Malasia: "MY",
  Malaui: "MW",
  Maldivas: "MV",
  Malí: "ML",
  Malta: "MT",
  Marruecos: "MA",
  Mauricio: "MU",
  Mauritania: "MR",
  México: "MX",
  Micronesia: "FM",
  Moldavia: "MD",
  Mónaco: "MC",
  Mongolia: "MN",
  Montenegro: "ME",
  Mozambique: "MZ",
  Namibia: "NA",
  Nauru: "NR",
  Nepal: "NP",
  Nicaragua: "NI",
  Níger: "NE",
  Nigeria: "NG",
  Noruega: "NO",
  "Nueva Zelanda": "NZ",
  Omán: "OM",
  "Países Bajos": "NL",
  Pakistán: "PK",
  Palaos: "PW",
  Panamá: "PA",
  "Papúa Nueva Guinea": "PG",
  Paraguay: "PY",
  Perú: "PE",
  Polonia: "PL",
  Portugal: "PT",
  "Reino Unido": "GB",
  "República Centroafricana": "CF",
  "República Checa": "CZ",
  "República del Congo": "CG",
  "República Democrática del Congo": "CD",
  "República Dominicana": "DO",
  Ruanda: "RW",
  Rumanía: "RO",
  Rusia: "RU",
  Samoa: "WS",
  "San Cristóbal y Nieves": "KN",
  "San Marino": "SM",
  "San Vicente y las Granadinas": "VC",
  "Santa Lucía": "LC",
  "Santo Tomé y Príncipe": "ST",
  Senegal: "SN",
  Serbia: "RS",
  Seychelles: "SC",
  "Sierra Leona": "SL",
  Singapur: "SG",
  Siria: "SY",
  Somalia: "SO",
  "Sri Lanka": "LK",
  Sudáfrica: "ZA",
  Sudán: "SD",
  "Sudán del Sur": "SS",
  Suecia: "SE",
  Suiza: "CH",
  Surinam: "SR",
  Tailandia: "TH",
  Tanzania: "TZ",
  Tayikistán: "TJ",
  "Timor Oriental": "TL",
  Togo: "TG",
  Tonga: "TO",
  "Trinidad y Tobago": "TT",
  Túnez: "TN",
  Turkmenistán: "TM",
  Turquía: "TR",
  Tuvalu: "TV",
  Ucrania: "UA",
  Uganda: "UG",
  Uruguay: "UY",
  Uzbekistán: "UZ",
  Vanuatu: "VU",
  Venezuela: "VE",
  Vietnam: "VN",
  Yemen: "YE",
  Yibuti: "DJ",
  Zambia: "ZM",
  Zimbabue: "ZW",
};
